# Generated by Django 4.2.13 on 2024-05-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainimages',
            options={'verbose_name_plural': 'Main Images'},
        ),
    ]
