# Generated by Django 4.2.13 on 2024-05-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0002_alter_mainimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(max_length=255)),
                ('dop_info', models.TextField(max_length=1000, null=True)),
                ('background', models.TextField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Performances',
            },
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('first_time', models.BooleanField(default=False)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.performance')),
            ],
            options={
                'verbose_name_plural': 'Performers',
            },
        ),
        migrations.CreateModel(
            name='Creatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.performance')),
            ],
            options={
                'verbose_name_plural': 'Creatives',
            },
        ),
    ]
