# Generated by Django 4.2.13 on 2024-05-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0003_performance_performers_creatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='subtitle',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
