# Generated by Django 4.2.13 on 2024-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0005_alter_performance_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performers',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
