# Generated by Django 4.2.13 on 2024-05-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0006_alter_performers_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='image',
            field=models.ImageField(null=True, upload_to='perfimg/'),
        ),
    ]
