# Generated by Django 4.2.13 on 2024-05-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0007_performance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='image',
            field=models.ImageField(upload_to='perfimg/'),
        ),
    ]
