# Generated by Django 4.2.13 on 2024-05-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0009_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='subtitle',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
