# Generated by Django 4.2.13 on 2024-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0012_backstage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backstage',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='backstage',
            name='video',
        ),
        migrations.AddField(
            model_name='backstage',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='backstage/'),
        ),
    ]
