# Generated by Django 4.2.13 on 2024-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0013_rename_description_backstage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstage',
            name='main_image',
            field=models.ImageField(null=True, upload_to='backstage/'),
        ),
    ]
