# Generated by Django 4.2.13 on 2024-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0014_backstage_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstage',
            name='main_image',
            field=models.ImageField(upload_to='backstage/'),
        ),
    ]
