# Generated by Django 4.2.13 on 2024-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0015_alter_backstage_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstage',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
