# Generated by Django 4.2.13 on 2024-05-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0016_backstage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backstage',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
