# Generated by Django 4.2.13 on 2024-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0020_alter_backstage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='backstage',
            name='type',
            field=models.CharField(choices=[('Статья', 'Статья'), ('Запись', 'Запись'), ('Подкаст', 'Подкаст')], default='Статья', max_length=10),
        ),
    ]
