# Generated by Django 4.2.13 on 2024-05-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0021_backstage_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backstage',
            old_name='content',
            new_name='block1_content',
        ),
        migrations.RenameField(
            model_name='backstage',
            old_name='media',
            new_name='block1_media',
        ),
        migrations.RenameField(
            model_name='backstage',
            old_name='picture',
            new_name='block1_picture',
        ),
        migrations.AddField(
            model_name='backstage',
            name='block1_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('media', 'Media')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block2_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block2_media',
            field=models.FileField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block2_picture',
            field=models.ImageField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block2_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('media', 'Media')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block3_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block3_media',
            field=models.FileField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block3_picture',
            field=models.ImageField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block3_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('media', 'Media')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block4_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block4_media',
            field=models.FileField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block4_picture',
            field=models.ImageField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block4_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('media', 'Media')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block5_content',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block5_media',
            field=models.FileField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block5_picture',
            field=models.ImageField(blank=True, null=True, upload_to='backstage/'),
        ),
        migrations.AddField(
            model_name='backstage',
            name='block5_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('media', 'Media')], default='text', max_length=10),
        ),
    ]
