# Generated by Django 4.2.13 on 2024-06-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0024_performance_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='premier',
            field=models.DateField(blank=True, null=True),
        ),
    ]
