# Generated by Django 4.2.13 on 2024-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0025_performance_premier'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='repertory_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='repertory_name',
            field=models.CharField(default='LL', max_length=255),
        ),
    ]
