# Generated by Django 4.2.13 on 2024-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0027_performance_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='datetime',
        ),
        migrations.AddField(
            model_name='performance',
            name='datetime1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='datetime2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
