# Generated by Django 4.2.13 on 2024-06-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0028_remove_performance_datetime_performance_datetime1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='datetime1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='datetime2',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
