# Generated by Django 4.2.13 on 2024-06-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0029_alter_performance_datetime1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
