# Generated by Django 4.2.13 on 2024-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0030_alter_performance_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainimages',
            name='title',
            field=models.CharField(default='me', max_length=100),
        ),
    ]
