# Generated by Django 4.2.13 on 2024-06-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0031_mainimages_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimages',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
