# Generated by Django 4.2.13 on 2024-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0032_alter_mainimages_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='percarousel/')),
            ],
        ),
        migrations.AddField(
            model_name='performance',
            name='image_carousel',
            field=models.ManyToManyField(blank=True, null=True, to='affiche.performancefiles'),
        ),
    ]
