# Generated by Django 4.2.13 on 2024-06-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0036_remove_performers_first_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performanceperformers',
            options={'verbose_name_plural': 'Performance Performers'},
        ),
    ]
