# Generated by Django 4.2.13 on 2024-06-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0037_alter_performanceperformers_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatives',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='creatives',
            name='role',
        ),
        migrations.CreateModel(
            name='PerformanceCreatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.creatives')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.performance')),
            ],
            options={
                'verbose_name_plural': 'Performance Creatives',
            },
        ),
    ]
