# Generated by Django 4.2.13 on 2024-06-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0039_remove_conductor_performance_performanceconductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceconductor',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiche.conductor'),
        ),
    ]
