# Generated by Django 4.2.13 on 2024-06-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0041_performancecreatives_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceperformers',
            old_name='performer',
            new_name='name',
        ),
    ]
