# Generated by Django 4.2.13 on 2024-06-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0043_performanceconductor_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performanceperformers',
            unique_together={('name', 'role', 'performance')},
        ),
    ]
