# Generated by Django 4.2.13 on 2024-06-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0044_alter_performanceperformers_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performanceperformers',
            unique_together={('role', 'performance')},
        ),
    ]
