# Generated by Django 4.2.13 on 2024-06-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiche', '0045_alter_performanceperformers_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performanceperformers',
            old_name='name',
            new_name='performer',
        ),
        migrations.AlterUniqueTogether(
            name='performanceperformers',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='performanceperformers',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
